In [1]:
import sys

parent_dir = 'Predict-Future-Sales'
p_sub = sys.path[0]

ride = ''
for path in p_sub.split('/'):
    if path != parent_dir:
        ride = ride + path + '/'
    else:
        ride = ride + path + '/'
        break
sys.path[0] = ride

import numpy as np
import pandas as pd
import torch

from module.lino_module.preprocess import mode_of_freq

from typing import Tuple, Optional, Union
from numpy import ndarray
from pandas import DataFrame, Series, DatetimeIndex
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from torch.utils.data import DataLoader
from torch.utils.data import TensorDataset

In [2]:
from module.lino_module.preprocess import univariate_dataset

data = pd.read_csv('../data/sales_train.csv')
data = mode_of_freq(data).item_cnt_day
demo = np.arange(len(data))
ds = pd.Series(demo , index=data.index)
ds

date
2013-01-01       0
2013-01-02       1
2013-01-03       2
2013-01-04       3
2013-01-05       4
              ... 
2015-10-27    1029
2015-10-28    1030
2015-10-29    1031
2015-10-30    1032
2015-10-31    1033
Freq: D, Length: 1034, dtype: int64

In [7]:
dataset_kw = {'data' : ds,
              'seq' : 7,
              'dilation' : 1,
              'src_tgt_seq' : (4, 3),
              'step_num' : 2,
              'scaler' : None,
              'daily' : True,
              'weekday' : True,
              'weekly' : True,
              'monthly' : True,
              'batch_size' : 64,
              'train_rate' : 0.9}

train, test = univariate_dataset(**dataset_kw)

In [8]:
src, tgt, label = next(iter(train))

In [9]:
src.shape, tgt.shape, label.shape

(torch.Size([64, 4, 5]), torch.Size([64, 3, 5]), torch.Size([64, 3]))

In [10]:
src[0], tgt[0], label[0]

(tensor([[0.0000, 0.0000, 0.1667, 0.0000, 0.0000],
         [2.0000, 0.0645, 0.5000, 0.0000, 0.0000],
         [4.0000, 0.1290, 0.8333, 0.0000, 0.0000],
         [6.0000, 0.1935, 0.0000, 0.0227, 0.0000]]),
 tensor([[ 8.0000,  0.2581,  0.3333,  0.0227,  0.0000],
         [10.0000,  0.3226,  0.6667,  0.0227,  0.0000],
         [12.0000,  0.3871,  1.0000,  0.0227,  0.0000]]),
 tensor([12., 13., 14.]))